name: Build PCF Solution

on:
  workflow_dispatch:
  push:
    paths:
      - 'CommentsControl/**'
      - '.github/workflows/build-pcf-solution.yml'

jobs:
  build-solution:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: (Optional) Install PCF dev deps for control
        working-directory: ./CommentsControl
        run: |
          npm ci

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Power Platform CLI (pac) as .NET tool
        run: |
          dotnet tool install -g Microsoft.PowerApps.CLI.Tool
          # add user tools to PATH for this job
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          pac --version

      - name: Create solution skeleton
        run: |
          mkdir solution
          cd solution
          pac solution init --publisher-name "The Alliance" --publisher-prefix ta

      - name: Add PCF control to solution
        run: |
          cd solution
          # path to the folder that contains ControlManifest.Input.xml
          pac solution add-reference --path ../CommentsControl

      - name: Build solution (Managed + Unmanaged)
        run: |
          cd solution
          # Build unmanaged
          msbuild /t:build /restore /p:Configuration=Debug
          # Build managed
          msbuild /t:build /restore /p:Configuration=Release /p:PackageType=Managed

      - name: Upload solution ZIPs
        uses: actions/upload-artifact@v4
        with:
          name: pcf-solution-zips
          path: |
            solution\bin\Debug\*.zip
            solution\bin\Release\*.zip
