name: Build PCF Solution

on:
  workflow_dispatch:
  push:
    paths:
      - 'CommentsControl/**'
      - '.github/workflows/build-pcf-solution.yml'

jobs:
  build-solution:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install control deps
        working-directory: ./CommentsControl
        run: npm ci

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Power Platform CLI (pac)
        run: |
          dotnet tool install -g Microsoft.PowerApps.CLI.Tool
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          pac --version

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Create solution skeleton
        run: |
          mkdir solution
          cd solution
          pac solution init --publisher-name "The Alliance" --publisher-prefix ta

      - name: Add PCF control to solution
        run: |
          cd solution
          pac solution add-reference --path ../CommentsControl

      - name: Build solution (Unmanaged + Managed)
        run: |
          cd solution
          msbuild /t:build /restore /p:Configuration=Debug
          msbuild /t:build /restore /p:Configuration=Release /p:PackageType=Managed

      - name: Upload solution zips
        uses: actions/upload-artifact@v4
        with:
          name: pcf-solution-zips
          path: |
            solution\bin\Debug\*.zip
            solution\bin\Release\*.zip
