name: Build PCF Solution

on:
  workflow_dispatch:
  push:
    paths:
      - 'CommentsControl/**'
      - '.github/workflows/build-pcf-solution.yml'

jobs:
  build-solution:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Power Platform CLI (pac)
        run: |
          dotnet tool install -g Microsoft.PowerApps.CLI.Tool
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          pac help | Out-Host   # don't use --version (can exit non-zero)

      - name: Scaffold clean PCF project in CI (dataset)
        run: |
          mkdir ci_pcf
          cd ci_pcf
          pac pcf init --namespace Comments --name CommentsControl --template dataset --framework none
          Get-ChildItem -Recurse -File | Select-Object FullName | Out-Host

      - name: Copy your code/manifest/resources into the scaffold
        run: |
          # Required files
          Copy-Item -Force "CommentsControl\index.ts" "ci_pcf\CommentsControl\index.ts"
          Copy-Item -Force "CommentsControl\ControlManifest.Input.xml" "ci_pcf\CommentsControl\ControlManifest.Input.xml"

          # strings.resx (if present)
          if (Test-Path "CommentsControl\strings\strings.resx") {
            New-Item -ItemType Directory -Force "ci_pcf\CommentsControl\strings" | Out-Null
            Copy-Item -F
