name: Build PCF Solution

on:
  workflow_dispatch:
  push:
    paths:
      - 'CommentsControl/**'
      - '.github/workflows/build-pcf-solution.yml'

jobs:
  build-solution:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install control deps
        working-directory: ./CommentsControl
        run: npm ci

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Power Platform CLI (pac)
        run: |
          dotnet tool install -g Microsoft.PowerApps.CLI.Tool
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          pac help | Out-Host   # don't use --version (non-zero exit sometimes)

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Verify PCF project layout
        run: |
          if (!(Test-Path "CommentsControl/ControlManifest.Input.xml")) {
            Write-Error "ControlManifest.Input.xml not found at CommentsControl/. Fix your repo layout and commit."
            exit 1
          }
          Get-ChildItem -Recurse -File CommentsControl | Select-Object FullName | Out-Host

      - name: Create solution skeleton
        run: |
          mkdir solution
          cd solution
          pac solution init --publisher-name TheAlliance --publisher-prefix ta
      
      - name: Add PCF control to solution (prefer folder, fallback to .pcfproj)
        run: |
          cd solution
          $ErrorActionPreference = 'Stop'
          if (Test-Path ../CommentsControl/ControlManifest.Input.xml) {
            Write-Host "Using ../CommentsControl (folder contains ControlManifest.Input.xml)"
            pac solution add-reference --path ../CommentsControl
            if ($LASTEXITCODE -ne 0) {
              Write-Warning "Folder add-reference failed; trying .pcfproj if present…"
              if (Test-Path ../Comments.pcfproj) {
                pac solution add-reference --path ../Comments.pcfproj
              } else {
                throw "No .pcfproj to fall back to."
              }
            }
          }
          elseif (Test-Path ../Comments.pcfproj) {
            Write-Host "Using ../Comments.pcfproj"
            pac solution add-reference --path ../Comments.pcfproj
          }
          else {
            Write-Error "No PCF project found. Ensure CommentsControl/ControlManifest.Input.xml or Comments.pcfproj exists."
            exit 1
          }


      - name: Build solution (Unmanaged + Managed)
        run: |
          cd solution
          msbuild /t:build /restore /p:Configuration=Debug
          msbuild /t:build /restore /p:Configuration=Release /p:PackageType=Managed

      - name: Dump PAC logs on failure
        if: failure()
        run: |
          $logs = Get-ChildItem "$env:USERPROFILE\.dotnet\tools" -Filter pac-log.txt -Recurse -ErrorAction SilentlyContinue
          if ($logs) {
            foreach ($l in $logs) {
              Write-Host "=== PAC LOG: $($l.FullName) ==="
              Get-Content $l.FullName -Raw | Write-Host
            }
          } else {
            Write-Host "No pac-log.txt found."
          }

      - name: Upload solution zips
        uses: actions/upload-artifact@v4
        with:
          name: pcf-solution-zips
          path: |
            solution\bin\Debug\*.zip
            solution\bin\Release\*.zip
